---
apiVersion: v1
kind: Namespace
metadata:
  name: proyecto-grupo-25
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: candidato
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: candidato
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: candidato
    spec:
      containers:
      - image: CANDIDATO_IMAGE
        imagePullPolicy: Always
        name: candidato
        ports:
        - containerPort: 5001
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: candidato-cb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: candidato-cb
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: candidato-cb
    spec:
      containers:
      - image: CANDIDATO_CB_IMAGE
        imagePullPolicy: Always
        name: candidato-cb
        ports:
        - containerPort: 5002
        env:
        - name: CAND_BACK_URL
          value: "http://service-candidato:5001"
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-candidato
spec:
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: candidato
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-candidato-cb
spec:
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: candidato-cb
---




apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: empresa
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: empresa
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: empresa
    spec:
      containers:
      - image: EMPRESA_IMAGE
        imagePullPolicy: Always
        name: empresa
        ports:
        - containerPort: 5003
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: empresa-cb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: empresa-cb
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: empresa-cb
    spec:
      containers:
      - image: EMPRESA_CB_IMAGE
        imagePullPolicy: Always
        name: empresa-cb
        ports:
        - containerPort: 5004
        env:
        - name: EMPR_BACK_URL
          value: "http://service-empresa:5003"
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-empresa
spec:
  ports:
    - port: 5003
      targetPort: 5003
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: empresa
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-empresa-cb
spec:
  ports:
    - port: 5004
      targetPort: 5004
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: empresa-cb
---






---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: perfil
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: perfil
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: perfil
    spec:
      containers:
      - image: PERFIL_IMAGE
        imagePullPolicy: Always
        name: perfil
        ports:
        - containerPort: 5005
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"
        - name: EMPR_BACK_URL
          value: "http://service-empresa-cb:5004"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: perfil-cb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: perfil-cb
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: perfil-cb
    spec:
      containers:
      - image: PERFIL_CB_IMAGE
        imagePullPolicy: Always
        name: perfil-cb
        ports:
        - containerPort: 5006
        env:
        - name: PERF_BACK_URL
          value: "http://service-perfil:5005"
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-perfil
spec:
  ports:
    - port: 5005
      targetPort: 5005
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: perfil
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-perfil-cb
spec:
  ports:
    - port: 5006
      targetPort: 5006
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: perfil-cb
---








---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: aplicacion
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aplicacion
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aplicacion
    spec:
      containers:
      - image: APLICACION_IMAGE
        imagePullPolicy: Always
        name: aplicacion
        ports:
        - containerPort: 5007
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"
        - name: PERF_BACK_URL
          value: "http://service-perfil-cb:5006"
        - name: CAND_BACK_URL
          value: "http://service-candidato-cb:5002"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: aplicacion-cb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: aplicacion-cb
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aplicacion-cb
    spec:
      containers:
      - image: APLICACION_CB_IMAGE
        imagePullPolicy: Always
        name: aplicacion-cb
        ports:
        - containerPort: 5008
        env:
        - name: APLI_BACK_URL
          value: "http://service-aplicacion:5007"
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-aplicacion
spec:
  ports:
    - port: 5007
      targetPort: 5007
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: aplicacion
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-aplicacion-cb
spec:
  ports:
    - port: 5008
      targetPort: 5008
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: aplicacion-cb
---

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: busqueda
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: busqueda
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busqueda
    spec:
      containers:
      - image: BUSQUEDA_IMAGE
        imagePullPolicy: Always
        name: busqueda
        ports:
        - containerPort: 5009
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:postgres@postgres.cfgkb3tpxr7g.us-east-1.rds.amazonaws.com:5432/postgres"
        - name: PERF_BACK_URL
          value: "http://service-perfil-cb:5006"
        - name: EMPR_BACK_URL
          value: "http://service-empresa-cb:5004"
        - name: CAND_BACK_URL
          value: "http://service-candidato-cb:5002"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: proyecto-grupo-25
  name: busqueda-cb
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: busqueda-cb
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busqueda-cb
    spec:
      containers:
      - image: BUSQUEDA_CB_IMAGE
        imagePullPolicy: Always
        name: busqueda-cb
        ports:
        - containerPort: 5010
        env:
        - name: APLI_BACK_URL
          value: "http://service-busqueda:5009"
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-busqueda
spec:
  ports:
    - port: 5009
      targetPort: 5009
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: busqueda
---
apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-grupo-25
  name: service-busqueda-cb
spec:
  ports:
    - port: 5010
      targetPort: 5010
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: busqueda-cb
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: proyecto-grupo-25
  name: ingress-proyecto-grupo-25
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /perfi
          pathType: Prefix
          backend:
            service:
              name: service-perfil-cb
              port:
                number: 5006
        - path: /candidato
          pathType: Prefix
          backend:
            service:
              name: service-candidato-cb
              port:
                number: 5002
        - path: /empresa
          pathType: Prefix
          backend:
            service:
              name: service-empresa-cb
              port:
                number: 5004
        - path: /login
          pathType: Prefix
          backend:
            service:
              name: service-empresa-cb
              port:
                number: 5004