# Ejemplo de github action para probar python
# Docs: https://docs.github.com/es/actions/using-workflows/workflow-syntax-for-github-actions
name:   CI PROYECTO

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3
      - name: Install environment candidatos
        working-directory: ./backend/candidato
        run: |
          pip install pipenv
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
      - name: Run unit tests candidatos
        working-directory: ./backend/candidato
        run: |
          pytest --cov=src -v -s --cov-fail-under=80
      - name: Install environment empresa
        working-directory: ./backend/empresa
        run: |
          pip install pipenv
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
      - name: Run unit tests empresa
        working-directory: ./backend/empresa
        run: |
          pytest --cov=src -v -s --cov-fail-under=80
      - name: Install environment perfil
        working-directory: ./backend/perfil
        run: |
          pip install pipenv
          pipenv sync --system --dev
          export VIRTUAL_ENV="$(pipenv --venv)" PATH="$(pipenv --venv)/bin:$PATH"
          export EMPR_BACK_URL=http://k8s-proyecto-ingressp-eb59205740-1747100398.us-east-1.elb.amazonaws.com
      - name: Run unit tests empresa
        working-directory: ./backend/empresa
        run: |
          pytest --cov=src -v -s --cov-fail-under=80

          